# ./github/workflows/deploy.yml

name: Deploy Middleman to GOVUK PaaS

on:
  push:
    branches:
      - "master"
      
  # Allows us to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build website
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Create diagrams folder
        run: | 
          mkdir ./screenshots 
          chmod -R 777 ./screenshots
	  whoami
  
      - name: Update Cloud workspace
        run: docker run --rm -v $(pwd):/usr/local/structurizr structurizr/cli push -id ${{ secrets.STRUCTURIZR_WORKSPACE_ID }} -key ${{ secrets.STRUCTURIZR_API_KEY }} -secret ${{ secrets.STRUCTURIZR_API_SECRET }} -workspace ./source-c4-diagrams/workspace.dsl

      - name: Publish diagrams
        run: docker run --shm-size 1G --rm -v $(pwd)/source-c4-diagrams/export-private-cloud-diagrams.js:/app/index.js -v $(pwd)/screenshots:/screenshots alekzonder/puppeteer:latest node index.js "https://structurizr.com" "${{ secrets.STRUCTURIZR_USERNAME }}" '${{ secrets.STRUCTURIZR_PASSWORD }}' png ${{ secrets.STRUCTURIZR_WORKSPACE_ID }}

      - name: Copy diagrams over
        run: |
          cp ./screenshots/structurizr-69325-SystemLandscape.png ./source/architecture/context/images/SystemLandscape.png
          cp ./screenshots/structurizr-69325-AcademyTransfersSystem-SystemContext.png ./source/architecture/context/images/SystemContext.png
          cp ./screenshots/structurizr-69325-AcademyTransfersSystem-Container.png ./source/architecture/containers/images/Containers.png
          cp ./screenshots/structurizr-69325-AmazonWebServicesDeployment.png ./source/architecture/deployment/images/Deployment-Live.png

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'

      - name: Ruby gem cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install Gems
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 13.x

      - name: Node packages cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install packages
        run: npm install

      - name: Build Middleman
        run: bundle exec middleman build

      - name: Deploy to GOVUK PaaS
        uses: citizen-of-planet-earth/cf-cli-action@master
        with:
          cf_api: ${{ secrets.CF_API_ENDPOINT }}
          cf_username: ${{ secrets.CF_USERNAME }}
          cf_password: ${{ secrets.CF_PASSWORD}}
          cf_org: ${{ secrets.CF_ORG }}
          cf_space: ${{ secrets.CF_SPACE }}
          command: push ${{ secrets.CF_APP_NAME }}
